# read: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: Nodejs

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm i

      - name: Build Packages
        run: npm run build
        
      - name: Download nanojsx
        run: curl https://raw.githubusercontent.com/nanojsx/nano/master/bundles/nano.full.min.js -o lib/nanojsx.min.js

      - name: Prepare Test
        run: |
          npm i -D puppeteer@14
          npx -y gitget nanojsx/nano/scripts/browserTest#v0.0.32  browserTest
          npx tsc -p browserTest/tsconfig.json

      - name: Test
        run: node browserTest/index.mjs --coverage

      - name: Coverage
        run: npx -y nyc report --exclude lib/nanojsx.min.js
